#!/bin/bash
# Copyright (c) 2025 ECMWF
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail


# Copy the upsteam driver to the image for further use file if one is set

sudo mkdir $TARGET_ROOT/opt/nvidia
cd $TARGET_ROOT/opt/nvidia
sudo curl -O https://nexus.ecmwf.int/repository/EWC-Common/nvidia-linux-grid-570-570.124.06-1.x86_64.rpm
