#!/bin/bash
# Copyright (c) 2023 ECMWF 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail 

echo "chkodebug2"

cat << 'EOF' > /etc/systemd/system/ecmwf-gpus.service
[Unit]
Description=ECMWF GPU Package Reinstallation After SSHD
After=sshd.service
Requires=sshd.service

[Service]
Type=oneshot
ExecStart=/bin/bash -c '/usr/bin/dnf reinstall -y /opt/nvidia/nvidia-linux-grid-570-570.124.06-1.x86_64.rpm | logger -t ecmwf-gpus'
ExecStartPost=/bin/systemctl disable ecmwf-gpus.service
RemainAfterExit=true

[Install]
WantedBy=multi-user.target
EOF

ls -alh /etc/systemd/system/

chown root:root /etc/systemd/system/ecmwf-gpus.service
chmod 644 /etc/systemd/system/ecmwf-gpus.service

systemctl daemon-reload
systemctl enable /etc/systemd/system/ecmwf-gpus.service
