#!/bin/bash
 
if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail
 
if [[ -n ${DIB_FINAL_RESOLV:-} ]]; then
   
    sudo cp ${DIB_FINAL_RESOLV} $TARGET_ROOT/etc/resolv.conf.ORIG
   
fi
